- hosts: "{{ host }}"

  tasks:
    - name: retrieve docker image
      docker_image:
        name: "upper/tour:{{ image_tag }}"
        force: yes
        state: present

    - name: run container
      docker_container:
        image: "upper/tour:{{ image_tag }}"
        name: upper-tour
        recreate: yes
        state: started
        ports:
          - 127.0.0.1:4000:4000
        restart_policy: always
        restart: true

    - name: test tour
      uri:
        url: http://127.0.0.1:4000/welcome/01
        method: GET
        status_code:
          - 200
          - -1
      register: result
      retries: 10
      delay: 5
      until: result.status == 200

    - name: add to docker network
      docker_network:
        name: upper-network
        state: present
        appends: yes
        connected:
          - upper-tour
