- hosts: "{{ host }}"

  tasks:
    - name: get legacy-docs
      docker_image:
        name: "upper/legacy-docs:{{ image_tag }}"
        force: yes
        state: present

    - name: run legacy-docs
      docker_container:
        image: "upper/legacy-docs:{{ image_tag }}"
        name: upper-legacy-docs
        recreate: yes
        ports:
          - 127.0.0.1:9000:9000

    - name: add to docker network
      docker_network:
        name: upper-network
        state: present
        appends: yes
        connected:
          - upper-legacy-docs

    - name: test legacy-docs
      uri:
        url: http://127.0.0.1/db.v3
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"

    - name: test legacy-docs
      uri:
        url: http://127.0.0.1/db.v2
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"

    - name: test legacy-docs
      uri:
        url: http://127.0.0.1/db.v1
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"
