- hosts: upper

  tasks:
    - name: get docs
      docker_image:
        name: upper/docs:{{ image_tag }}
        force: yes
        state: present

    - name: run docs
      docker_container:
        image: upper/docs:{{ image_tag }}
        name: upper-docs
        recreate: yes
        ports:
          - 127.0.0.1:9000:9000

    - name: add to docker network
      docker_network:
        name: upper-network
        state: present
        appends: yes
        connected:
          - upper-docs

    - name: test docs
      uri:
        url: http://127.0.0.1/db.v3
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"

    - name: test docs
      uri:
        url: http://127.0.0.1/db.v2
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"

    - name: test docs
      uri:
        url: http://127.0.0.1/db.v1
        method: GET
        status_code:
          - 200
        headers:
          Host: upper.io
        return_content: yes
      register: this
      failed_when: "'DOCTYPE' not in this.content"
