# Configuration file for Luminos.     https://menteslibres.net/luminos
server:
  bind: "0.0.0.0"
  port: 9000
  type: "standalone"

hosts:
  /db.v1: "./upper.io/v1"
  /db.v2: "./upper.io/v2"
  /db.v3: "./upper.io/v3"
  default: "./upper.io/default"
